# Generated by Django 2.1 on 2020-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6)),
                ('age', models.CharField(default='0', max_length=4)),
                ('password', models.CharField(default='', max_length=50)),
                ('identity_id', models.CharField(default='', max_length=18)),
                ('true_name', models.CharField(default='', max_length=18)),
            ],
        ),
    ]
