# Generated by Django 2.1 on 2020-11-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=18)),
                ('formula', models.CharField(default='', max_length=500)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=6)),
            ],
        ),
    ]
