# Generated by Django 2.1 on 2020-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0002_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='pinyin',
            field=models.CharField(default='', max_length=18),
        ),
    ]
