# Generated by Django 2.1 on 2020-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0003_pack_pinyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], default='A', max_length=6),
        ),
    ]
