# Generated by Django 2.1 on 2020-11-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0004_auto_20201119_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='pinyin',
        ),
    ]
