# Generated by Django 2.1 on 2020-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0005_remove_pack_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='area',
            field=models.CharField(default='', max_length=500),
        ),
    ]
