# Generated by Django 2.1 on 2020-11-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0007_auto_20201119_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='string',
            field=models.CharField(default='', max_length=100),
        ),
    ]
