# Generated by Django 2.1 on 2020-11-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0008_pack_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='contrast',
            field=models.TextField(default='', max_length=100),
        ),
    ]
