# Generated by Django 2.1 on 2020-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0010_auto_20201120_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='contrast',
            field=models.TextField(default='{"L":"长（cm）","W":"宽（cm）","H":"高（cm）","S":"侧（cm）","T":"厚度（丝）","N":"数量（个）","C":"几色","G":"克重（g）","B":"底（cm）",}', max_length=400),
        ),
    ]
