# Generated by Django 2.1 on 2020-11-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0011_auto_20201120_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='category',
        ),
    ]
