# Generated by Django 2.1 on 2020-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_price', '0013_pack_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(default='', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
